apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-service
  labels:
    app: node-js
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-js
  template:
    metadata:
      labels:
        app: node-js
    spec:
      containers:
        - name: node-js
          image: lenolium/backend
          ports:
            - containerPort: 4000