apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-js
  template:
    metadata:
      labels:
        app: react-js
    spec:
      containers:
        - name: react-js
          image: lenolium/frontend
          env:
            - name: REACT_APP_BACKEND_URL
              value: 'http://127.0.0.1:{port}/'
          ports:
            - containerPort: 3000